# Site settings
title: Patrick Newell
description: 'a place for stuff'
url: 'http://www.pmnewell.com'
baseurl: ''
google_analytics: 'UA-45875189-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Pat Newell'
  email: patrick@pmnewell.com
  twitter_username: pnewell4
  facebook_username: pmnewell
  github_username:  pmn4
  linkedin_username:  pmnewell

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
